// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Js_primitive = require("bs-platform/lib/js/js_primitive.js");
var Storage = require("@google-cloud/storage");

var default_config = { };

function init($staropt$star, _) {
  var config = $staropt$star !== undefined ? Js_primitive.valFromOption($staropt$star) : default_config;
  var gcs = Storage(config);
  var request = function (ops) {
    ops.forever = false;
    return ops;
  };
  var interceptor = {
    request: request
  };
  gcs.interceptors.push(interceptor);
  return gcs;
}

function getSignedUrl(config, file, cb) {
  file.getSignedUrl(config, cb);
  return /* () */0;
}

function Storage_001(prim, prim$1) {
  return prim.bucket(prim$1);
}

function Storage_002(prim, prim$1) {
  return prim.file(prim$1);
}

function Storage_003(prim) {
  return prim.createReadStream();
}

function Storage_004(prim) {
  return prim.createWriteStream();
}

var Storage$1 = [
  init,
  Storage_001,
  Storage_002,
  Storage_003,
  Storage_004,
  getSignedUrl
];

exports.Storage = Storage$1;
/* @google-cloud/storage Not a pure module */
